### ISSUE TITLE
TLAB events create misleading flame graphs

### ISSUE THREAD

**Issue by oehme** [chrishantha/jfr-flame-graph#10]
Using `-e allocation-tlab` seems to count the allocation events instead of counting the amount of memory allocated at that stack frame. This means that the flamegraph will show stacks that allocate often, even if they only allocate a few bytes.

As a user I'd expect the flamegraph to point me to the stacks that actually consumed the most memory.

**Comment by oehme** [comment]
Nevermind, the recording I looked at must have been bad. I tried with a few others and see actual memory usage being shown as expected.

**Comment by oehme** [comment]
Okay I know now where the problem is. The converter currently reads the "allocationSize" field, which only contains the size of the object that triggered a new TLAB to be created. That doesn't tell you though how much memory this type of object is taking up overall. The converter should use the "tlabSize" field instead.

**Comment by chrishantha** [comment]
Hi @oehme, I'm really sorry for the delay. I will check on this soon and reply. I'm also happy to accept a PR if you can fix the code. :smile:

**Comment by oehme** [comment]
You can take a look at my [fork](https://github.com/oehme/jfr-flame-graph), it contains a couple of improvements:

- tlab allocations now measure the tlabSize, the size is converted to kB
- io and blocking are now measured by their duration instead of their count
- the code for labeling and unit conversion is now in the EventType enum
- the project is now built with Gradle so that there is a 1-step install process 
- broken stack frames no longer crash the tool
