### ISSUE TITLE
jfr-flame-graph don't complain when com.jrockit.mc.common_* is not in plugins 

### ISSUE THREAD

**Issue by crakjie** [chrishantha/jfr-flame-graph#13]
iI just leave an incorrect version in the file.
```
cat jmc_version.properties 
jmc.version=*
```

Another question that came with it. How can com.jrockit.mc.common be procurred?
Is com.oracle.jmc.core be use insteed?

**Comment by chrishantha** [comment]
Hi @crakjie, I will check on this.

**Comment by dwo** [comment]
Sorry to resurrect an old issue but I was wondering a similar thing. If I run `./gradlew installDist` I see:
```
> No Java Mission Control found in /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
```

Is this because OpenJDK doesn't come with these jars (but Oracle does)?

**Comment by shhrohan** [comment]
i am getting the same issue.

**Comment by chrishantha** [comment]
Closing this issues as it's not relevant anymore.
