### ISSUE TITLE
Support official JFR APIs

### ISSUE THREAD

**Issue by crakjie** [chrishantha/jfr-flame-graph#14]
With java 9 jrockit jars changed name.
This making incompatibility with jfr-flame-graph

**Comment by chrishantha** [comment]
Hi @crakjie, Thanks for creating an issue on this. I will check on this.

**Comment by retronym** [comment]
Sort of relatedly, Java 10 now has an [official API](https://docs.oracle.com/javase/10/docs/api/jdk/jfr/consumer/package-summary.html) for consuming flight recording profiles

**Comment by leogomes** [comment]
AFAIK the official api cannot read JFR files generated with previous versions of Java. JMC core jars have been open sourced and will be on maven central soon. With that you will be able to read any JFR recording from 7 to the latest JDK.

**Comment by cykl** [comment]
Hi @leogomes. Are you planning to support Java 11 or aware of any project doing so? If not I might create a jfr-flame-graph for Java 11 based on OpenJDK API.

**Comment by chrishantha** [comment]
Hi @cykl, I have plans to support latest official APIs

**Comment by retronym** [comment]
Noting that the backport of Flight Recorder to  OpenJDK8u262 uses the new format and also isn't supported by jfr-flamegraph.

**Comment by chrishantha** [comment]
@retronym Thank you for informing. I was a bit away from Java for several months. I'm hoping to work on supporting official APIs soon.

**Comment by jtjeferreira** [comment]
Submitted a PR for this https://github.com/chrishantha/jfr-flame-graph/pull/24. It worked for my use case...

**Comment by chrishantha** [comment]
Thanks a lot @jtjeferreira! Your changes are in the `main` branch now.
