### ISSUE TITLE
ERROR: No valid input provided to flamegraph.pl.

### ISSUE THREAD

**Issue by Allchin** [chrishantha/jfr-flame-graph#17]
hi ,

 ----------------------my os is windows 7  and in my SourceTree  Cygwin  command line ,i try install this  jfr-flame-graph ----------------

 ./gradlew assemble

 ----------------------after installed  , i fund the jar name is not correct on my path-------
$  ./create_flamegraph.sh -f /e/temp/output3Dump.jfr -i > /e/temp/flame.svg
Error: Unable to access jarfile ./build/libs/jfr-flamegraph-*-all.jar
ERROR: No stack counts found

$ cd build/libs/
$ ls
jfr-flamegraph-0.0.3-SNAPSHOT.jar
------------------------then i modified the jar name at  flamegraph-output.sh  and  run again ------

$  ./create_flamegraph.sh -f /e/temp/output3Dump.jfr -i > /e/temp/flame.svg
./build/libs/jfr-flamegraph-0.0.3-SNAPSHOT.jar▒▒û▒▒▒▒▒嵥▒▒▒▒
ERROR: No stack counts found

-------------------------and i get error  message  in the svg  file.--------------
ERROR: No valid input provided to flamegraph.pl

**Comment by chrishantha** [comment]
Hi @Allchin,

Please check the master branch now. The build and install instructions were changed. Please make sure to follow the README. Thanks!
