### ISSUE TITLE
Cannot resolve JMC dependencies

### ISSUE THREAD

**Issue by plokhotnyuk** [chrishantha/jfr-flame-graph#8]
[ERROR] Failed to execute goal on project flamegraph-output: Could not resolve dependencies for project com.github.chrishantha.jfr:flamegraph-output:jar:0.0.3-SNAPSHOT: The following artifacts could not be resolved: com.jrockit.mc:com.jrockit.mc.common:jar:5.5.1.172852, com.jrockit.mc:com.jrockit.mc.flightrecorder:jar:5.5.1.172852: Could not find artifact com.jrockit.mc:com.jrockit.mc.common:jar:5.5.1.172852 in repo (file:///home/andriy/Projects/com/github/chrishantha/jfr-flame-graph/repo) -> [Help 1]

**Comment by chrishantha** [comment]
Did you run install-mc-jars.sh script as mentioned in the README?

**Comment by shhrohan** [comment]
where is this `install-mc-jars.sh` file in repo ?
